name = "stb_image"
version = "1.0.0"
license = "MIT"
author = "Lewis McMillan"
maintainer = "lewisfish92"
copyright = "2020 Lewis McMillan"

[library]
source-dir="src"

[build]
auto-executables = false

#[[ executable ]]
#name="main"
#source-dir="app"
#main="main.f90"

#[[ executable ]]
#name="test_image"
#source-dir="app"
#main="image_main.f90"
